# Generated by Django 4.0.3 on 2022-03-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
